# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Used Cars' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Used Cars
  pod 'Alamofire'
  pod 'EAAlert'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Kingfisher', '~> 7.0'

end
